# Generated by Django 5.2 on 2025-05-14 17:26

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Category slug')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('dete_modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Tile')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('source_url', models.URLField(verbose_name='Source url')),
                ('availability', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, default='', max_length=5000, verbose_name='Description')),
                ('old_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Price before discount')),
                ('price', models.PositiveIntegerField(verbose_name='Current price')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Discount')),
                ('image_urls', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(verbose_name='Image source url'), default=list, size=None)),
                ('is_images_uploaded', models.BooleanField(default=False)),
                ('categories', models.ManyToManyField(related_name='products', to='store.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=255, upload_to='images/product')),
                ('url', models.URLField(verbose_name='Image source url')),
                ('size', models.PositiveIntegerField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=100, verbose_name='Reviewer name')),
                ('comment', models.CharField(max_length=1000, verbose_name='Comment text')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.product')),
            ],
        ),
    ]
