# Generated by Django 5.2 on 2025-05-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.CharField(max_length=5000, verbose_name='Comment text'),
        ),
    ]
